# Generated by Django 4.0.6 on 2022-07-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('device_os', models.CharField(blank=True, max_length=200, null=True)),
                ('device_browser', models.CharField(blank=True, max_length=200, null=True)),
                ('device_type', models.CharField(blank=True, max_length=200, null=True)),
                ('device_model', models.CharField(blank=True, max_length=200, null=True)),
                ('site_url', models.CharField(blank=True, max_length=200, null=True)),
                ('referrer_url', models.CharField(blank=True, max_length=200, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=1000, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=200, null=True)),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True)),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True)),
                ('location_country', models.CharField(blank=True, max_length=200, null=True)),
                ('location_region', models.CharField(blank=True, max_length=200, null=True)),
                ('location_city', models.CharField(blank=True, max_length=200, null=True)),
                ('location_zip', models.CharField(blank=True, max_length=200, null=True)),
                ('user_ip', models.CharField(blank=True, max_length=200, null=True)),
                ('views', models.IntegerField(blank=True, default=1, null=True)),
                ('user_id', models.UUIDField(editable=False)),
                ('device_id', models.UUIDField(editable=False)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
